name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate YAML encoding
      run: |
        echo "Checking encoding for YAML files..."
        file -i .github/workflows/dotnet.yml | grep 'charset=utf-8'
        echo "Checking encoding for test files..."
        find . -name '*.cs' -exec file -i {} \; | grep 'charset=utf-8'
        echo "Checking for non-UTF-8 characters..."
        find . -name '*.cs' -exec cat {} \; | grep -P '[^\x00-\x7F]' || echo "No non-UTF-8 characters detected"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
