name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Ensure files are UTF-8 encoded
      run: |
        echo "Checking encoding for YAML and C# files..."
        # Check YAML encoding
        if file -bi .github/workflows/dotnet.yml | grep -q 'charset=utf-8'; then
          echo "YAML file is encoded in UTF-8."
        else
          echo "YAML file is not encoded in UTF-8."
          exit 1
        fi
        # Check C# files encoding
        for file in $(find . -name '*.cs'); do
          if file -bi "$file" | grep -q 'charset=utf-8'; then
            echo "$file is encoded in UTF-8."
          else
            echo "$file is not encoded in UTF-8."
            exit 1
          fi
        done

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
